services:
  lucy:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
    environment:
      DB_HOST: "${DOCKER_DB_HOST}"
      DB_PORT: '5432'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DOCKER_DB_PASSWORD}'
      DB_NAME: '${DOCKER_DB_NAME}'
      PORT: '${PORT}'
      LAST_FM_API_KEY: '${LAST_FM_API_KEY}'
      CLIENT_SECRET: '${CLIENT_SECRET}'
      CLIENT_ID: '${CLIENT_ID}'
    depends_on:
      - postgres
    networks:
      - alice

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: quantinium
      POSTGRES_DB: postgres
    volumes:
      - lucy_db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - alice

volumes:
  lucy_db: {}

networks:
  alice: {}
